version: "1"

volumes:
  mongodb_volume

services:
  device-monitoring:
    build: NotificationService
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - TZ=Europe\Samara
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - LANGUAGE=RU

  mongodb:
    image:mongo:latest
    volumes:
      - mongodb_volume:/data/db
    estart: always


