volumes:
  mongodb_volume:

services:
  notificator:
    build: NotificationService/
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Europe\Samara
      - MONGO_DB_ADDR=mongodb
      - MONGO_DB_PORT=27017
      - LANGUAGE=RU

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always